### ISSUE TITLE
Missing references

### ISSUE THREAD

**Issue by RyanOC** [SamMurray381/Fluent-Migrator-Example#1]
There are some missing references. I think it must be a Model project that it missing. Would you be able to look into it and add it? Thanks for the FluentMigration example code!

**Comment by SamMurray381** [comment]
Hi Ryan, thank you for bringing this to my attention!

I've fixed the reference issue now, let me know if you have any other problems with the code.

Cheers, 
Sam.

**Comment by RyanOC** [comment]
Sam, It builds fine now. Thanks again!
